apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botamin-postgres-data
  namespace: botamin-voice
  labels:
    app.kubernetes.io/name: botamin-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: botamin-voice
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme.network-drives.csi.timeweb.cloud
  resources:
    requests:
      storage: 5Gi
