apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-start-edge
  namespace: rec-sidecar
spec:
  template:
    spec:
      nodeSelector:
        ai-native-paas.io/pool: ci
      imagePullSecrets:
        - name: craas-ai-native-paas-registry
      containers:
        - name: caddy
          image: ai-native-paas-registry.registry.twcstorage.ru/mirror/legacy/caddy@sha256:b95ed06fbc6d74d24a40902090c8cc6086ce7d08ba60a3a7e8e62bf164a9d7bb
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          $patch: replace
          persistentVolumeClaim:
            claimName: clean-start-edge-caddy-data
